version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
         
     - run: time docker pull python:3.6
         
     # build the application image
     - run: docker build -t jimmyzhang/python-test:main .
     # deploy the image
     - run: docker push jimmyzhang/python-test:main
