version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         docker login --username $DOCKER_USERNAME --password "$DOCKER_PASSWORD"

     # build the application image
     - run: docker build -t jimmyzhang/python-test:main .

     # deploy the image
     - run: docker push jimmyzhang/python-test:main
